ALTER TABLE elektrons_candidates
MODIFY COLUMN score INT(6) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE skimmers_candidates
MODIFY COLUMN score INT(6) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE clovers_candidates
MODIFY COLUMN score INT(6) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE redbolts_candidates
MODIFY COLUMN score INT(6) UNSIGNED NOT NULL DEFAULT 0;